#pragma config(Motor,  port1,           frontRight,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           extender,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           hook,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftJack1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftJack2,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "LittleBotFunctions.h";
task test(){
	motor[arm1] = 127;
	motor[arm2] = 127;
	wait10Msec(100);

}
task main()
{
	int threshold = 10;
	int extenderDistance = 100;
	int AMOUNT = 1;
	int hookDistance = 100;
	while(true){
	//	if(abs(vexRT[Ch1] > threshold){
	//	}
	//	else{
	//	}
		if(abs(vexRT[Ch2]) > threshold){
			setRight(vexRT[Ch2]/AMOUNT);
		}
		else{
			setRight(0);
		}
		if(abs(vexRT[Ch3]) > threshold){
			setLeft(vexRT[Ch3]/AMOUNT);
		}
		else{
			setLeft(0);
		}
		//if(abs(vexRT[Ch4]) > threshold){
		//	setArm(vexRT[Ch4]/AMOUNT);
		//}
		//else{
		//	setArm(0);
		//}
		if(vexRT[Btn7L] == 1){
			setArm(127);
			while(vexRT[Btn7L] == 1);
			setArm(0);
		}
		else if(vexRT[Btn7D] == 1){
			setArm(-127);
			while(vexRT[Btn7D] == 1);
			setArm(0);
		}
		if(vexRT[Btn8D] == 1){
			motor[extender] = 127;
			while(vexRT[Btn8D] == 1);
			motor[extender] = 0;
		}
		else if(vexRT[Btn8R] == 1){
			motor[extender] = -127;
			while(vexRT[Btn8R]==1);
			motor[extender] = 0;
		}
		if(vexRT[Btn6D] == 1){
			motor[hook] = 64;
			while(vexRT[Btn6D]==1);
			motor[hook] = 0;
		}
		else if(vexRT[Btn6U] == 1){
			motor[hook] = -64;
			while(vexRT[Btn6U]==1);
			motor[hook] = 0;
		}
		if(vexRT[Btn5D] == 1){
			liftJack(64);
			while(vexRT[Btn5D]==1);
			liftJack(0);
		}
		else if(vexRT[Btn5U] == 1){
			liftJack(-64);
			while(vexRT[Btn5U]==1);
			liftJack(0);
		}
	}
}
