#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setRight(int speed){
	motor[backRight] = speed;
	motor[frontRight] = speed;
}
void setLeft(int speed){
	motor[frontLeft] = speed;
	motor[backLeft] = speed;
}

task main()
{
	int threshold = 10; // threshold is the value that should be considered zero
	int AMOUNT = 1; // AMOUNT is the amount to devide the number by. higher AMOUNT will make the joystick less sensitive.
	while(true){
		/* RIGHT JOYSTICK */
		if(abs(vexRT[Ch2]) > threshold){
			setRight(vexRT[Ch2]/AMOUNT);
		}
		else{
			setRight(0);
		}
		/* LEFT JOYSTICK */
		if(abs(vexRT[Ch3]) > threshold){
			setLeft(vexRT[Ch3]/AMOUNT);
		}
		else{
			setLeft(0);
		}
	}
}
