#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    redBlueSwitch,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Sensor, dgtl4,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, dgtl4)
#pragma config(Motor,  port4,           hook,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           extender,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           wench,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftJack1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftJack2,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "LittleBotFunctionsEncoder.h";
task main()
{
	while(vexRT[Btn8D] == 0);
	motor[hook] = -127;
	wait10Msec(60);
	motor[hook] = 64;
	wait10Msec(200);
	motor[hook] = 0;
	while(vexRT[Btn8D] == 0);
	turnCW(170, 127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(2.1,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	turnCCW(150, 127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(2,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(1.7,-127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	turnCW(130,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(1.1,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	turnCCW(140,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(1.85,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(.7,-127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	turnCCW(45,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
	move(1.5,127);
	wait10Msec(1);
	while(vexRT[Btn8D] == 0);
}
