#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    redBlueSwitch,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, dgtl2)
#pragma config(Motor,  port4,           hook,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           extender,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           wench,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftJack1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftJack2,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "LittleBotFunctionsEncoder.h";
task main()
{
	int threshold = 10;
	int AMOUNT = 1;
	while(true){
		if(abs(vexRT[Ch2]) > threshold){
			setRight(vexRT[Ch2]/AMOUNT);
		}
		else{
			setRight(0);
		}
		if(abs(vexRT[Ch3]) > threshold){
			setLeft(vexRT[Ch3]/AMOUNT);
		}
		else{
			setLeft(0);
		}
		if(vexRT[Btn7L] == 1){
			setArm(127);
			while(vexRT[Btn7L] == 1);
			setArm(0);
		}
		else if(vexRT[Btn7D] == 1){
			setArm(-127);
			while(vexRT[Btn7D] == 1);
			setArm(0);
		}
		if(vexRT[Btn7U] == 1){
			setArm(127);
			motor[wench] = 127;
			while(vexRT[Btn7U] == 1);
			setArm(0);
			motor[wench] = 0;
		}
		else if(vexRT[Btn7R] == 1){
			motor[wench] = 127;
			while(vexRT[Btn7R] == 1);
			motor[wench] = 0;
		}
		if(vexRT[Btn8U] == 1){
			turnCW(150,127);
		}
		if(vexRT[Btn8D] == 1){
			motor[extender] = 127;
			while(vexRT[Btn8D] == 1);
			motor[extender] = 0;
		}
		else if(vexRT[Btn8R] == 1){
			motor[extender] = -127;
			while(vexRT[Btn8R]==1);
			motor[extender] = 0;
		}
		if(vexRT[Btn6D] == 1){
			motor[hook] = 64;
			while(vexRT[Btn6D]==1);
			motor[hook] = 0;
		}
		else if(vexRT[Btn6U] == 1){
			motor[hook] = -64;
			while(vexRT[Btn6U]==1);
			motor[hook] = 0;
		}
		if(vexRT[Btn5D] == 1){
			liftJack(127);
			while(vexRT[Btn5D]==1);
			liftJack(0);
		}
		else if(vexRT[Btn5U] == 1){
			liftJack(-127);
			while(vexRT[Btn5U]==1);
			liftJack(0);
		}
	}
}
