#pragma config(Motor,  port5,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm2,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setArm(int speed){
	motor[arm1] = speed;
	motor[arm2] = speed;
}

task main()
{
	setArm(127);
	wait10Msec(500);
	setArm(0);
}
